version: "3.8"

# run commands inside here with: 
# docker-compose run ansible bash
# if you want to run an ansible command, replace bash with ansible (yes, two times ansible in a row)
# example command: 
# docker-compose run ansible ansible all -m ping -u you 

services: 
    ansible: 
        build: .
        volumes:
            - ./ansible/hosts:/etc/ansible/hosts
            - ./ansible/playbooks/:/opt/ansible-workdir